### ISSUE TITLE
win10下postgres容器挂载volume失败-wrong ownership

### ISSUE THREAD

**Issue by hellozhang** [generals-space/note-cloud#1]
如果我希望D盘某个目录挂载数据，比如postgresql 的执行初始化脚本，

**Comment by hellozhang** [comment]
version: '3'
services:
  postgres-svc:
    image: postgres:11
    ports:
    - "5432:5432"
    ## win下挂载路径可能会出错
    environment:
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      ## 初始化脚本目录
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbscript:/script

**Comment by hellozhang** [comment]
比如我想初始化脚本，initdb文件夹内，这样可能

**Comment by hellozhang** [comment]
V:\dockervolume>docker-compose up
Creating dockervolume_postgres-svc_1 ... done
Attaching to dockervolume_postgres-svc_1
postgres-svc_1  | The files belonging to this database system will be owned by user "postgres".
postgres-svc_1  | This user must also own the server process.
postgres-svc_1  |
postgres-svc_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres-svc_1  | The default database encoding has accordingly been set to "UTF8".
postgres-svc_1  | The default text search configuration will be set to "english".
postgres-svc_1  |
postgres-svc_1  | Data page checksums are disabled.
postgres-svc_1  |
postgres-svc_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres-svc_1  | creating subdirectories ... ok
postgres-svc_1  | selecting default max_connections ... 20
postgres-svc_1  | selecting default shared_buffers ... 400kB
postgres-svc_1  | selecting default timezone ... Asia/Shanghai
postgres-svc_1  | selecting dynamic shared memory implementation ... posix
postgres-svc_1  | creating configuration files ... ok
postgres-svc_1  | running bootstrap script ... 2020-06-10 10:08:02.056 CST [81] FATAL:  ****data directory "/var/lib/postgresql/data" has wrong ownership****
postgres-svc_1  | 2020-06-10 10:08:02.056 CST [81] HINT:  The server must be started by the user that owns the data directory.
postgres-svc_1  | child process exited with exit code 1
postgres-svc_1  | initdb: removing contents of data directory "/var/lib/postgresql/data"
dockervolume_postgres-svc_1 exited with code 1

**Comment by generals-space** [comment]
我的文章里有说明, 在 docker-compose.yaml 中只能通过`volume`声明 postgres 的数据卷, 但我没找到数据卷和初始化脚本同时挂载的方法. 

如果你实在想这样做, 可以考虑进入到运行 docker 的 linux 主机中去看看(windows上的docker其实是用 Hyper-V 运行了一个linux主机来运行的)

**Comment by generals-space** [comment]
事实上, 从这个问题之后, 我就再也没有使用过 docker-for-win 和 docker-for-mac 了, 太误事, 都是在 linux 虚拟机上再装 docker 用的...

**Comment by hellozhang** [comment]
ok，多谢回复，我也找了很久，没有答案。
